import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@/config/query-client";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <nav className="text-white">
            <Link href="/">Home</Link>
            <Link href="/settings">Settings</Link>
            <input type="text" className="text-black" />
          </nav>
          {children}
        </body>
      </html>
    </QueryClientProvider>
  );
}
